const managerPermissions = [
  'createMachines',
  'editMachines',
  'deleteMachines',
  'createProducts',
  'editProducts',
  'deleteProducts',
  'transferProducts',
  'createCategories',
  'editCategories',
  'deleteCategories',
  'listGroups',
  'createGroups',
  'editGroups',
  'deleteGroups',
  'createPointsOfSale',
  'editPointsOfSale',
  'deletePointsOfSale',
  'createRoutes',
  'editRoutes',
  'deleteRoutes',
  'listManagers',
  'listOperators',
  'createManagers',
  'createOperators',
  'editManagers',
  'editOperators',
  'deleteManagers',
  'deleteOperators',
  'toggleMaintenanceMode',
  'editCollections',
  'deleteCollections',
  'addRemoteCredit',
  'generateReports',
];

export default managerPermissions;
